### PR TITLE
I18 pages

### LINKED ISSUE #73: i18n Pages
Currently, `harmonic new_page` correctly generates a new markdown file inside each `src/pages/[lang]`, but `harmonic build` will only output a single rendered version. It looks like all languages are being written to the same location and overwrite each other.

That is, the pages are written to `public/pages/[slug]/index.html` when it should be `public/pages/[lang]/[slug]/index.html`.

Also, shouldn't there be some kind of listing/indexing of pages? Or is the user supposed to link to them in the layout manually?

### PR DESCRIPTION
**Pull request by viniciusdacal**
fixed #73 
Sorry about creating a new branch instead of using `i18n_fix` created by @jaydson , but I tried to use that and I got many conflict.

### CODE REVIEW

**Comment by viniciusdacal** [comment]
@UltCombo

**Comment by UltCombo** [comment]
The `i18n_fix` branch was not merged and diverged a lot (or rather, `master` diverged a lot from it), so it was actually better to create a new branch.
I will review/test soon. :smile:

**Comment by UltCombo** [comment]
Works great!
Awesome job.

**Comment by viniciusdacal** [comment]
Thanks man :smile:

**Comment by UltCombo** [comment]
Two notes:
- We should now be able to write the [tests for `harmonic new_page`](https://github.com/JSRocksHQ/harmonic/blob/49604f8ede14cbef8a081bab754d570a95c78caf/src/test/main.js#L112). It should be pretty similar to the `new_post` ones. Perhaps, in the future, we can even abstract it away so both of them use (most of) the same core logic.
- The [default harmonic theme](https://github.com/JSRocksHQ/harmonic-theme-default)'s `page` template displays the page title twice in its body content. That one should be easy to fix.

I'm adding the "needs tests" label to remind that there's still a TODO regarding the pages.

**Comment by viniciusdacal** [comment]
tests added in #165

**Comment by jaydson** [comment]
Thanks for working on it @viniciusdacal !

**Pull request merged**
