### PR TITLE
supported dynamic templates

### PR DESCRIPTION
**Pull request by viniciusdacal**
@UltCombo @jaydson 
Review needed

### CODE REVIEW

**Comment by viniciusdacal** [comment]
#164

**Comment by UltCombo** [comment]
Nice work!
It would be nice if we moved the `metadata.layout` normalization to the [`normalizeMetaData` function](https://github.com/JSRocksHQ/harmonic/blob/b871ce2638396cd92a792af09ff07c60de878527/src/bin/parser.js#L36), by adding a `defaultLayout` parameter to it.

**Comment by UltCombo** [comment]
Or we could think ahead a bit and add a `defaults` parameter which receives an object.

**Comment by viniciusdacal** [comment]
Yeah, that is a great idea. @UltCombo. 
I made de changes, could you check?

**Comment by UltCombo** [comment]
Nice! :smile:
I just did a full review, excellent work @viniciusdacal!
I've added some small adjustments as well: https://github.com/JSRocksHQ/harmonic/commit/cb6a021847905b3a9456dd9ca8d37466229ed27e (please comment if you find anything out of order).

It would be nice to have an unit test for custom layouts, so I'm tagging this issue with "needs tests" so we don't end up forgetting.

We can make a new Harmonic release once we update the [wiki page](https://github.com/JSRocksHQ/harmonic/wiki/Markdown-Header). That wiki page seems a little outdated though, we should fully revise it. (cc @jaydson)

**Comment by UltCombo** [comment]
@viniciusdacal By the way, would you like to have Contributor status in the Harmonic repository?

Regardless of your decision, we will not push responsibilities onto you, we don't want to force you to contribute more than what you're already doing. With Contributor status, though, you will be able to help revising PRs and shaping the future of Harmonic.

So what do you think?

**Comment by viniciusdacal** [comment]
@UltCombo of course, it would be a pleasure to have a contributor status :smiley:
Very thanks.

**Comment by UltCombo** [comment]
I've sent an invitation, GitHub should mail you shortly. Welcome aboard! :tada:

**Comment by viniciusdacal** [comment]
I already received here.
Really thanks :smile:

**Comment by jaydson** [comment]
Welcome @viniciusdacal, and thanks for the awesome work you're doing, man.
Let's evolve this beast called Harmonic :smiling_imp:

**Comment by viniciusdacal** [comment]
:metal: :)

**Comment by jaydson** [comment]
We can release a new version within this new feature.

I think the Wiki page is fine, @UltCombo.
Perhaps just add the new property and document it properly.

**Comment by UltCombo** [comment]
@jaydson There are some other things that seem outdated to me. The `published` metadata is now always supported independent of the theme, right? It is also missing some properties such as `authorPicture` (or is this supposed to be a custom property?).

**Comment by jaydson** [comment]
I DUNNO.
This headers thing was poorly implemented at first (my fault, again).
Looking close now, I think we should isolate the defaults and custom properties.
I mean, the `title` is the post title Harmonic uses internally, but what if the user remove it? Or what if the user add a `Title` property?
Well, this works just fine for now, but we can improve those headers properties a lot.

Perhaps we should have `defaults` and `custom` properties, or something like that.

What do you guys think?

**Pull request merged**
