### PR TITLE
fixed pages var structure and fixed page link

### PR DESCRIPTION
**Pull request by viniciusdacal**

### CODE REVIEW

**Comment by UltCombo** [comment]
Awesome!
Nice catch, now `generatePosts` and `generatePages` are even more alike. We should see what we can abstract from there sometime.

**Comment by UltCombo** [comment]
We should publish a new Harmonic version after we pull the latest es20xx updates and write the changelog.
I will most likely be able to do that tomorrow, if I don't have to work overtime.

**Comment by jaydson** [comment]
That'd be great @UltCombo

**Comment by UltCombo** [comment]
@jaydson @viniciusdacal https://github.com/JSRocksHQ/harmonic/releases/tag/v0.5.1

**Pull request merged**
